get:
  parameters:
  - name: type
    description: The `recordType DeveloperName` of product
    in: query
    required: true
    schema:
      $ref: 'schemas.yaml#/components/schemas/type'
  tags: 
    - Products
  summary: get list of products by record type
  responses:
    200:
      description: The list of products corresponding to the provided `type`
      content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  description: A false value to indicate an error
                  type: boolean
                  default: true
                message:
                  description: A human-readable error message
                  type: string
                products:
                  description: A array of product fields
                  type: array
                  items:
                    $ref : 'schemas.yaml#/components/schemas/Product2'
    404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: 'schemas.yaml#/components/schemas/Error'
    500:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: 'schemas.yaml#/components/schemas/Error'
  